### ISSUE TITLE
Missing validation for max lenght of word

### ISSUE THREAD

**Issue by BrunoMollo** [adrielgorosito/Metodologias-agiles-TP#3]
While playing the game, the UI can display a maximum of 16 `_` characters but you can pick a word with a bigger lenght that cant be fully displayed. For example here is how the word "constitucionalizacion" is shown:
![image](https://github.com/adrielgorosito/Metodologias-agiles-TP/assets/48107910/23a29325-b48e-469f-89dc-7c9accaac077)

This issue should be solved adding a validation on the max length of the word or by extending the length the display

**Comment by adrielgorosito** [comment]
Fixed, thanks!
