### ISSUE TITLE
Word that is impossible to guess

### ISSUE THREAD

**Issue by BrunoMollo** [adrielgorosito/Metodologias-agiles-TP#4]
As expected, some validations are made when the player is guessing words. For example `*` is not a valid character to guess. But this validations are not aplied when the word is chosen. Therefore one player can chose the word `****` and the other player while never be able to guess it because can guess `*` as a letter. However it can win by guessing the full word.

**Comment by adrielgorosito** [comment]
Fixed, thanks!

**Comment by adrielgorosito** [comment]
Fixed, thanks!
