### ISSUE TITLE
Bug when selecting many times the same letter

### ISSUE THREAD

**Issue by BrunoMollo** [adrielgorosito/Metodologias-agiles-TP#5]
The video attached to this issue might be clear enough. It seems like when choosing the same letter many times the lives are no reduced, but when a different letter is selected all the lives are substracted.

https://github.com/adrielgorosito/Metodologias-agiles-TP/assets/48107910/e4a4affd-cca4-421f-bf66-e21b61bfe868

**Comment by adrielgorosito** [comment]
**You didn't see anything**
